apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: spring
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: springboot3k8s:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
#          env:
#            - name: GREETING_PREFIX
#              valueFrom:
#                secretKeyRef:
#                  name: spring-boot
#                  key: greeting
#              value: Hello
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-boot-configmap
#                  key: greeter.prefix
      restartPolicy: Always
